// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/hidnt/fconv/internal/adapters"
	"github.com/hidnt/fconv/internal/service"
)

// Injectors from wire.go:

func InitializeService() service.ConverterService {
	imageConverter := adapters.NewImageConverter()
	videoConverter := adapters.NewVideoConverter()
	musicConverter := adapters.NewMusicConverter()
	mus2VidConverter := adapters.NewMus2VidConverter()
	v := adapters.ProvideConverters(imageConverter, videoConverter, musicConverter, mus2VidConverter)
	converterService := service.NewConverterService(v)
	return converterService
}
